config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations} #, :sessions => :sessions

  post "send_consult", to: "frontend#send_consult" , as: :send_consult
  get 'backend' => 'backend#index', as: :backend
  root 'frontend#index'

  get 'get_product/:id' => 'frontend#get_product', as: :get_product
  get 'get_work/:id' => 'frontend#get_work', as: :get_work

end

app/models/concerns/destroyable.rb
module Destroyable

  extend ActiveSupport::Concern

  included do
    def destroyable?
      true
    end

    def destroy
      super if destroyable?
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:home, :sign_in]
end

app/controllers/frontend_controller.rb
# -*- coding: utf-8 -*-
class FrontendController < ApplicationController


  def index
    @joke = params[:joke]
  end


	#-----------------------------------------------------------------------------------
	def send_consult

      if(! params[:name_surname].blank?) && (! params[:email].blank?) && (! params[:comments].blank?)
        @status = true

        ConsultMailer.send_consult(params).deliver
        flash.clear
        flash[:notice] = 'Mensaje Enviado'
      else
        @status = false
        flash.clear
        flash[:error] = 'Completar Campos'
      end

      respond_to do |format|
        format.js
      end
	end

  #-----------------------------------------------------------------------------------
  def get_product
    @product = {}
    case params[:id].to_i
    when 1
      #teytu
      @product[:img] = 'product-teytu.png'
      @product[:name] = 'Tecnología de Turismo'
    when 2
      #gestion
      @product[:img] = 'product-gestion.png'
      @product[:name] = 'Gestión de Empresas'
    when 3
      #torneos
      @product[:img] = 'product-torneos.png'
      @product[:name] = 'Gestión para Torneos'
    end
  end

  #-----------------------------------------------------------------------------------
  def get_work
    @work = {}
    case params[:id].to_i
    when 1
      @work[:name] = 'Aero'
      @work[:img] = 'aero.png'
      @work[:kind] = 'Sistema'
      @work[:text] = '<p>Aero es uno de los principales operadores de turismo de Argentina.</p>
       <p>Desarrollamos una aplicación para la gestión de reservas de aéreos y paquetes turísticos. La misma resuelve toda la operatoria de la organización a la vez que se encarga de la integración con sistemas preexistentes.</p>'
    when 2
      @work[:name] = 'Ministerio de Economia'
      @work[:img] = 'min.png'
      @work[:kind] = 'Web Mobile'
      @work[:text] = '<p>Fuimos el equipo a cargo de la adaptación de la web del Ministerio de Economía de la provincia de Buenos Aires.</p>
       <p>El trabajo se baso en el análisis, diagramación, maquetación e implementación del nuevo sitio mobile.</p>'
    when 3
      @work[:name] = 'Infoauto'
      @work[:img] = 'infoauto.png'
      @work[:kind] = 'Web + Sistema'
      @work[:text] = '<p>Infoauto es la página de consulta de rodados más visitada de Argentina, considerada en el rubro como la guía oficial de precios.</p>
       <p>Implementamos la nueva web y su versión mobile junto con un backend que satisface todos los requisitos para la auto-gestión de la misma.</p>'
    when 4
      @work[:name] = 'La Piedad'
      @work[:img] = 'lapiedad.png'
      @work[:kind] = 'Sistema'
      @work[:text] = '<p>Es una de las panaderías con mayor prestigio y tradición de la ciudad de La Plata.</p>
       <p>Desarrollamos e implementamos un sistema de gestión y puestos de venta con terminales touch screen para la gestión de la panadería.</p>'
    when 5
      @work[:name] = 'Proyecciones Digitales'
      @work[:img] = 'proyecciones.png'
      @work[:kind] = 'Web + Sistema'
      @work[:text] = '<p>Proyecciones Digitales es una de las empresas de mayor trayectoria brindando soluciones audiovisuales del país.</p>
       <p>Implementamos su nuevo sitio web institucional con el correspondiente backend que cubre todos las necesidades para la auto-gestión del mismo.</p>'
    when 6
      @work[:name] = 'Farmacia Zorich'
      @work[:img] = 'zorich.png'
      @work[:kind] = 'Sistema'
      @work[:text] = '<p>Farmacia Zorich es una empresa líder en el mercado de la salud de la ciudad de La Plata.</p>
      <p style="margin-bottom: 5px;">Los trabajos realizados para la farmacia fueron:</p>
      <ul>
        <li>Integración de ERP interno con sistema de puntos y promociones (Woowap)</li>
      </ul>
      <p style="margin-bottom: 5px;">Actualmente nos encontramos trabajando en:</p>
      <ul>
        <li>Integración de ERP interno con sistema de gestión y reportes contables.</li>
        <li>Integración de ERP interno con sistema de gestión financiero y gestión de ventas.</li>
        <li>Sistema de control y arqueo de stock integrable a ERP interno.</li>
      </ul>'

    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	skip_before_filter :set_breadcrumbs

  def new
    redirect_to :backend
  end

  protected

  def after_update_path_for(resource)
    backend_path
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message(klass, message)
    klass = 'success' if klass == 'notice' || klass == 'alert'
    flash.discard(klass)
    content_tag :article, class: "alert alert-#{klass}" do
      concat close_button(:alert)
      concat message
    end
  end

  def flash_messages
    flash.map do |type, message|
      flash_message(type, message)
    end.join.html_safe
  end

  def close_button(target = :modal)
    link_to '&times;'.html_safe, '', class: :close, data: {dismiss: target}
  end

  def icon(name, html_options={})
    html_options[:class] = ['fa', "fa-#{name}", html_options[:class]].compact
    content_tag(:i, nil, html_options)
  end

  def icon_left(name, string)
    (content_tag(:i, nil, class: "fa fa-#{name} margin-right-5") + string)
  end

  def icon_right(name, string)
   (string + content_tag(:i, nil, class: "fa fa-#{name} margin-left-5")).html_safe
 end

end

app/views/backend/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<%= link_to image_tag('backend/logos/snappler-logo-white.png', style: 'height: 100%;'), root_path, class: 'navbar-brand' %>
	</div>
	<div class="navbar-collapse collapse navbar-inverse-collapse">

    <!--
        <ul class="nav navbar-nav">
            <li class="active"><a href="javascript:void(0)">Active</a></li>
            <li><a href="javascript:void(0)">Link</a></li>
            <li class="dropdown">
                <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0)">Action</a></li>
                    <li><a href="javascript:void(0)">Another action</a></li>
                    <li><a href="javascript:void(0)">Something else here</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Dropdown header</li>
                    <li><a href="javascript:void(0)">Separated link</a></li>
                    <li><a href="javascript:void(0)">One more separated link</a></li>
                </ul>
            </li>
        </ul>
      -->

      <% if(user_signed_in?) %>
      <ul class="nav navbar-nav navbar-right">
      	<li class="dropdown">
      		<a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown"><%= icon_left(:user, current_user.email) %> <b class="caret"></b></a>
      		<ul class="dropdown-menu">
      			<li><%= link_to icon_left(:cog, 'Editar Perfil'), edit_user_registration_path %></li>

      			<li class="divider"></li>
      			<li><%= link_to icon_left(:reply, 'Salir'), destroy_user_session_path, method: :delete %></li>
      		</ul>
      	</li>
      </ul>
      <% end %>



    </div>
  </div>

app/views/backend/_side.html.erb
<aside class="col-md-3">
	<ul class="well nav nav-pills nav-stacked">
		<li><%= link_to icon_left(:home, t(:home)) , backend_path %></li>
	</ul>
</aside>

app/views/backend/index.html.erb
BACKEND

app/views/frontend/_contact_form.html.erb
<%= form_tag send_consult_path, method: :post, :authenticity_token => true, :remote => true, class: "form-horizontal", :id => 'express_contact' do %>

<div class="form-group">
	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1"><%= icon(:user) %></span>
		<input type="text" class="form-control" name="name_surname" id="name_surname" placeholder="Nombre" aria-describedby="basic-addon1">
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<span class="input-group-addon" id="basic-addon2"><i class="fa fa-envelope" style="height: 14px; width: 11px;"></i></span>
		<input type="text" class="form-control" name="email" id="email" placeholder="E-Mail" aria-describedby="basic-addon2">
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<span class="input-group-addon" id="basic-addon3"><%= icon(:phone) %></span>
		<input type="text" class="form-control" name="telephone" id="telephone" placeholder="Teléfono" aria-describedby="basic-addon3">
	</div>
</div>

<div class="form-group">
	<textarea type="text" class="form-control" name="comments" id="comments" placeholder="Escriba su mensaje..."></textarea>
</div>

<div class="form-group">
	<button type="submit" data-disable-with="Enviando..." class="btn btn-primary btn-sm pull-right">Enviar</button>
</div>
<% end %>

app/views/frontend/_navigation.html.erb
 <!-- Navigation -->
 <nav class="navbar navbar-default navbar-fixed-top">
 	<div class="container">
 		<!-- Brand and toggle get grouped for better mobile display -->
 		<div class="navbar-header page-scroll">
 			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
 				<span class="sr-only">Toggle navigation</span>
 				<span class="icon-bar"></span>
 				<span class="icon-bar"></span>
 				<span class="icon-bar"></span>
 			</button>
 			<a class="navbar-brand page-scroll " href="#page-top">
 				<%= image_tag 'frontend/logos/snappler-logo-white.png', style: 'height: 100%;' %>
 			</a>
 		</div>

 		<!-- Collect the nav links, forms, and other content for toggling -->
 		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 			<ul id="nav-iteml-list" class="nav navbar-nav navbar-custom">
 				<li class="hidden">
 					<a class="page-scroll ga_event_tracking" href="#page-top"></a>
 				</li>
 				<li class="nav-what">
 					<a class="page-scroll ga_event_tracking" href="#what">¿Qué hacemos?</a>
 				</li>
 				<li class="nav-how">
 					<a class="page-scroll ga_event_tracking" href="#how">¿Cómo lo hacemos?</a>
 				</li>
 				<li class="nav-products">
 					<a class="page-scroll ga_event_tracking" href="#products">Productos</a>
 				</li>
 				<li class="nav-works">
 					<a class="page-scroll ga_event_tracking" href="#works">Portfolio</a>
 				</li>
 				<li class="nav-team">
 					<a class="page-scroll ga_event_tracking" href="#team">Nosotros</a>
 				</li>
 				<li class="nav-contact">
 					<a class="page-scroll ga_event_tracking" style="padding-top: 10px; padding-bottom: 10px;" href="#contact"><i class="fa fa-envelope-o  fa-2x"></i></a>
 				</li>
 			</ul>
 		</div>
 		<!-- /.navbar-collapse -->
 	</div>
 	<!-- /.container-fluid -->
 </nav>

app/views/frontend/_product_item.html.erb
<div class="col-sm-6 col-md-4 portfolio-item">
  <a href="<%= product[:url] %>" class="portfolio-link" target="_blank">
    <div class="portfolio-hover">
      <div class="portfolio-hover-content">
        <i class="fa fa-plus fa-3x"></i>
      </div>
    </div>
    <%= image_tag "frontend/products/#{product[:img]}" %>
  </a>
  <div class="portfolio-caption">
    <h4><%= product[:kind] %></h4>
    <p class="text-muted"><%= product[:legend] %></p>
  </div>
</div>

app/views/frontend/_section_alerts.html.erb
<div style="display:none;" id="alert-success" class="alert alert-success" role="alert">
  <i class="fa fa-check  fa-2x"></i>
  <b>E-mail enviado</b>
</div>

<div style="display:none;" id="alert-warning" class="alert alert-danger" role="alert">
  <i class="fa fa-warning  fa-2x"></i>
  <b>Falta completar el Formulario</b>
</div>

app/views/frontend/_section_contact.html.erb
<!-- what Section -->
<section id="contact" class="bg-light-gray">

	<div class="bg-white head">
		<h3 class="section-heading">Contáctenos</h3>
		<hr class="custom-hr">
	</div>



	<div class="row contact-container">
	<div class="col-md-offset-1 col-md-11">
			<div class="row" style="padding-top: 20px; padding-bottom: 20px;">
				<div class="col-md-12">
					<span class="info-box" style="margin-right: 15px;"><i class="fa fa-map-marker"></i>Diagonal 79 N° 1042 - La Plata - Buenos Aires</span>
					<span class="info-box" style="margin-right: 15px;"><i class="fa fa-phone"></i>(0221) 15-616-1830</span>
					<span class="info-box" style="margin-right: 15px;"><i class="fa fa-envelope"></i>info@snappler.com</span>
					<span class="info-box" style="margin-right: 15px;"><a href="https://www.facebook.com/snappler.develop" target="_blank" ><i class="fa fa-facebook"></i>Snappler</a></span>
				</div>
			</div>
		</div>

		<div class="col-md-7 col-md-offset-1">
			
			<div class="row">
				<div class="col-md-6">
					<%= render 'contact_form' %>
				</div>

				<div class="col-md-6" style="text-align: center;">
					<%= image_tag "frontend/logos/snappler-legend.png", style: 'width: 50%; padding-bottom: 30px; padding-top: 10px; width: 50%;' %>
				</div>
			</div>
		</div>


	</div>







</section>

app/views/frontend/_section_how.html.erb
<!-- what Section -->
<section id="how" class="bg-violet">
  <div class="bg-white head">
    <h3 class="section-heading">¿Cómo lo hacemos?</h3>
    <hr class="custom-hr">
  </div>

  <div class="decor-bottom decor-white">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 100 100" version="1.1" preserveAspectRatio="none" height="100%" class="decor">
      <path stroke-width="0" d="M0 0 L100 100 L100 0 "/>
    </svg>
  </div>

  <div class="container" style="padding-bottom: 50px; padding-top: 25px;">
    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <p class="large text-muted text-justify">Con un fuerte compromiso y participación con el cliente, en cada nuevo
          desafío buscamos comprender todo el proyecto, para lograr una solución óptima para cada necesidad y detectar
          oportunidades de mejora.</p>

        <p class="large text-muted text-justify type2">Nuestro modelo de trabajo se basa en 5 etapas que se
          retroalimentan continuamente:</p>
      </div>
      <div class="col-md-4 col-md-offset-1">
        <div class="row">
          <div class="col-md-12 text-center">
            <%= image_tag 'frontend/who/como-lo-hacemos.png', class: 'graf', style: 'max-width:100%;' %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <%= image_tag 'frontend/banda1.jpg', style: 'width:100%;' %>


  <!-- <div class="decor-top decor-gray">
     <svg class="decor" height="100%" preserveAspectRatio="none" version="1.1" viewBox="0 0 100 100" width="100%" xmlns="http://www.w3.org/2000/svg"><path d="M0 100 L100 0 L100 100" stroke-width="0"/></svg>
   </div> -->

</section>

app/views/frontend/_section_modals.html.erb
<!-- Portfolio Modal 1 -->
<div class="portfolio-modal modal fade" id="productModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">

    <div class="decor-modal decor-green">
      <svg class="decor" height="100%" preserveAspectRatio="none" version="1.1" viewBox="0 0 100 100" width="100%" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 0 L100 100 L100 0 " stroke-width="0"/>
      </svg>
    </div>

    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">

          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- Portfolio Modal 1 -->
<div class="portfolio-modal modal fade" id="workModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">

    <div class="decor-modal decor-red">
      <svg class="decor" height="100%" preserveAspectRatio="none" version="1.1" viewBox="0 0 100 100" width="100%" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 0 L0 100 L100 0 " stroke-width="0"/>
      </svg>
    </div>

    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/frontend/_section_products.html.erb
<!-- what Section -->
<section id="products" class="bg-green">

  <div class="bg-gray head">

    <h3 class="section-heading">Productos</h3>
    <hr class="custom-hr">

  </div>

  <div class="decor-bottom decor-gray">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 100 100" version="1.1" preserveAspectRatio="none" height="100%" class="decor">
      <path stroke-width="0" d="M0 0 L0 100 L100 0"/>
    </svg>
  </div>

  <div class="container" style="padding-bottom: 50px; padding-top: 25px;">

    <div class="row">

      <div class="col-xs-10 col-xs-offset-1">

        <div class="row">
          <%= render 'product_item', product: {id: 1, img: 'product-teytu.png', kind: 'Sistema', legend: 'Tecnología de Turismo', url: 'http://www.teytu.com'} %>
          <%= render 'product_item', product: {id: 2, img: 'product-gestion.png', kind: 'Sistema', legend: 'Gestión de Empresas', url: 'http://www.snappler.com/showroom/snap-gestion/index.html'} %>
          <%= render 'product_item', product: {id: 3, img: 'product-torneos.png', kind: 'Sistema', legend: 'Gestión para Torneos', url: 'http://www.snappler.com/showroom/snap-torneos/index.html'} %>
        </div>

      </div>


    </div>


  </div>


</section>

app/views/frontend/_section_team.html.erb
<!-- what Section -->
<section id="team" class="bg-white2">

  <div class="bg-violet head">
    <h3 class="section-heading">Nosotros</h3>
    <hr class="custom-hr">
  </div>

  <div class="decor-bottom decor-violet">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 100 100" version="1.1" preserveAspectRatio="none" height="100%" class="decor">
      <path stroke-width="0" d="M0 0 L0 100 L100 0"/>
    </svg>
  </div>

  <div class="container" style="padding-bottom: 50px; padding-top: 25px;">
    <div>
      <div class="col-md-8 col-md-offset-2  text-center">
        <p class="large text-muted">
          Somos una empresa Argentina del sector TICs con más de 7 años de experiencia aportando ideas y soluciones a
          proyectos con diferentes características y necesidades.
        </p>
        <p class="large text-muted">
          <b>Tecnología de Punta, Gente de Primera</b>
        </p>
      </div>
    </div>

    <div style="margin-top:50px;">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="row" style="margin-bottom:30px;">
            <%= render 'team_profile', profile: {name: 'Francisco Peña', img: "fran#{rand(2)}.jpg"} %>
            <%= render 'team_profile', profile: {name: 'Juan P. La Battaglia', img: "juan#{rand(2)}.jpg"} %>
            <%= render 'team_profile', profile: {name: 'Verónica Marchi', img: "vero#{rand(2)}.jpg"} %>

            <%= render 'team_profile', profile: {name: 'Damian Grimberg', img: "dami#{rand(2)}.jpg"} %>
            <%= render 'team_profile', profile: {name: 'Gaston Ambrogi', img: "gasti#{rand(2)}.jpg"} %>
            <%= render 'team_profile', profile: {name: 'Mauro La Battaglia', img: "mauro#{rand(2)}.jpg"} %>

            <%= render 'team_profile', profile: {name: 'Nicanor Perera', img: "nica#{rand(2)}.jpg"} %>
            <%= render 'team_profile', profile: {name: 'Nicolás Galdámez', img: "nico#{rand(2)}.jpg"} %>
            <%= render 'team_profile', profile: {name: 'Esteban Suarez', img: "este#{rand(2)}.jpg"} %>

            <%= render 'team_profile', profile: {name: 'Matias E. Szeinfeld', img: "mati#{rand(2)}.jpg"} %>

            

          </div>
        </div>
      </div>

    </div>
    <div style="margin-top:50px;">
      <div class="col-md-8 col-md-offset-2  text-center">
        <p class="large text-muted">
          Somos un equipo multidisciplinario formado por profesionales y estudiantes del área Informática y
          Administración con gran capacidad y experiencia en la implementación de soluciones tecnológicas.
        </p>
      </div>
    </div>

  </div>
</section>

app/views/frontend/_team_profile.html.erb
<div class="col-xs-6 col-sm-4" style="margin-bottom: 10px;">
  <div class="team-member">
    <%= image_tag "frontend/team/#{profile[:img]}", class: 'img-responsive img-circle' %>
    <span class="tooltip-content">
      <h4><%= profile[:name] %></h4>
    </span>
  </div>
</div>

app/views/frontend/_work_item.html.erb
<div class="col-sm-6 col-md-4 portfolio-item">
  <a href="#workModal" class="portfolio-link work-link" data-id="<%= work[:id] %>" data-toggle="modal">
    <div class="portfolio-hover">
      <div class="portfolio-hover-content">
        <i class="fa fa-plus fa-3x"></i>
      </div>
    </div>
    <%= image_tag "frontend/works/#{work[:img]}" %>
  </a>

  <div class="portfolio-caption">
    <h4><%= work[:kind] %></h4>

    <p class="text-muted"><%= work[:legend] %></p>
  </div>
</div>

app/views/frontend/_work_modal.html.erb
<h2><%= @work[:name] %></h2>
<p class="item-intro text-muted"><%= @work[:kind] %></p>

<div class="row">

  <div class="col-sm-3 text-center">
    <%= image_tag "frontend/works/#{@work[:img]}", class: 'img-responsive' %>
  </div>

  <div class="col-sm-9 text-left">
    <%= @work[:text].html_safe %>
  </div>

</div>


<button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Volver</button>

app/views/frontend/get_product.js.erb
$('#productModal .modal-body').html('<%= escape_javascript(render 'product_modal') %>');

app/views/frontend/index.html.erb
<%= render 'navigation' %>
<%= render 'sliders' %>

<%= render 'section_what' %>
<%= render 'section_iram' %>
<%= render 'section_how' %>
<%= render 'section_products' %>
<%= render 'section_works' %>
<%= render 'section_team' %>
<%= render 'section_contact' %>

<%= render 'section_alerts' %>
<%= render 'section_modals' %>



<% unless @joke.nil? %>

    <%= audio_tag('chewbacca.mp3', id: 'chewbacca') %>

    <script>
        $(document).ready(function () {
            $(document).on('click', '.team-member .img-circle', function () {
                $('#chewbacca')[0].play();
            });
            $('.team-member .img-circle').addClass('fa fa-spin');
        });
    </script>

<% end %>

app/views/layouts/_analytics.html.erb
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        },i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-61993995-1', 'auto');
    ga('send', 'pageview');

    $('#nav-iteml-list').on('click', '.ga_event_tracking', function (event) {
        if (event.defaultPrevented) return;

        ga('send', 'event', 'menu', 'click', this.href);
    });

</script>

app/views/layouts/_g_analytics.html.erb
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        },i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-61993995-1', 'auto');
    ga('send', 'pageview');

    $('#nav-iteml-list').on('click', '.ga_event_tracking', function (event) {
        if (event.defaultPrevented) return;

        ga('send', 'event', 'menu', 'click', this.href);
    });

</script>

app/views/layouts/_g_tag_manager.html.erb
<!-- Google Tag Manager -->
<noscript>
  <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MPSH39"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<script>(function (w, d, s, l, i) {
    w[l] = w[l] || [];
    w[l].push({
        'gtm.start': new Date().getTime(), event: 'gtm.js'
    });
    var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
    j.async = true;
    j.src =
            '//www.googletagmanager.com/gtm.js?id=' + i + dl;
    f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-MPSH39');</script>
<!-- End Google Tag Manager -->